### ISSUE TITLE
記事編集画面 設定されているタグを消すアイコン？が正常に表示されていない

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#105]
![貼り付けた画像_2020_08_21_2_22](https://user-images.githubusercontent.com/870716/90804817-b5cc1e80-e355-11ea-8e1a-9e718c1a7841.png)

`/css/jquery/jquery-ui/1.9.2/themes/ui-lightness/images/ui-icons_222222_256x240.png`にある想定だが、同一ファイル名でしらべると`public/js/elrte/css/smoothness/images/ui-icons_222222_256x240.png`にある。

**Comment by fc2dev** [comment]
@uzulla 
パスが誤っていると想定されますので、修正いただいて構いません。

**Comment by uzulla** [comment]
@fc2dev 

承知いたしました、追って修正させていただきます。
（もしよろしければ、本件以外もGoなものはassigneしていただけますと間違いがなくて助かります）

**Comment by uzulla** [comment]
#168 にて対応したためクローズ
