### ISSUE TITLE
検討 エントリ削除エンドポイントのPOST化

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#109]
記事一覧からの記事削除リンク（更新処理）がGETで実装されているのに多少の違和感がある。

具体的には以下のようなURLにアクセスで削除ができる。
`http://localhost:8080/admin/entries/delete?id=3&sig=zO94Wt0Zc_ZoiyH2`

`sig`（≒CSRF Token）がアクセスログ（や、HTTPの場合は経由するProxyなど）にも残るのが微妙と思うが、削除成功などで`/admin/entries/index`へもどれば振り直されるので悪用は難しそうではある。優先順位的には低い。

（`sig`が毎回更新されるのは安全とも言えるが、複数タブでつかっていると少々不便さもある。ヘビーユーザー的なニーズとは思うが。）

## 実装方法
一括削除のために表はFORMでくくられているので、FORMを局地的に置けない。

外にFORMをつくり、JSをつかってentry_idを代入して隠しFormをPOSTさせるようにすればよいと思われる（現状も、削除確認ダイアログでJSをつかっている）

**Comment by fc2dev** [comment]
@uzulla 
お手隙の時にPOST化していただければと思います。
