### ISSUE TITLE
<%template_copyright_date> で $_SERVER['REQUEST_TIME'] が利用されているので削除したい

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#110]
https://github.com/fc2blog/blog/blob/8dc48927e88656331d36d1fbb11be302c192954e/app/config/fc2_template.php#L401

- 不要な$_SERVERはできるだけ減らしたい
- 「現在時刻」を取得したいだけなら、これは省略できる

ので、進めているユニットテストブランチで削除します。
なにか深い意味があれば指摘ください。

## 具体的なコード

「生成時点」での年月をいれるようになっているので、以下を予定しております。

```
  '<%template_copyright_date>' => date('Y'),
```

ただ、これ系でよくあるのは以下なので、もし以下が想定しているものであれば指摘ください。
（テンプレートの編集・保存・変換時でなく、ページ表示時の年を挿入するというもの）

```
  '<%template_copyright_date>' => '<?php echo date(\'Y\'); ?>',
```

**Comment by uzulla** [comment]
#101 の中に、修正したものがふくまれています

**Comment by fc2dev** [comment]
@uzulla 
この表示は何を意図しているのかはわかりませんが、
同じ動作をさせるということで、前者の方でご対応いただいているので
その対応で問題ありません。

**Comment by uzulla** [comment]
マージありがとうございました、クローズします。
