### ISSUE TITLE
コメントの「編集」リンクは編集不能ならば表示を消すべきではないか？

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#128]
コメントの「編集」は、パスワード未指定時にはクリックしたらそのブログトップへリダイレクトされるが、すこし分かりづらい気がする。
編集したくて編集を押すと、なにもエラーなくブログトップに遷移してしまう。

![貼り付けた画像_2020_08_31_12_49](https://user-images.githubusercontent.com/870716/91681104-5ad1cd00-eb88-11ea-822c-667375fa55ea.png)

https://github.com/fc2blog/blog/blob/51c1d54070cc951a19d41723eea922214d1a8a86/app/src/Web/Controller/User/EntriesController.php#L760-L766

編集不可能だと、リダイレクトをかけている。（この事自体は良い）

https://github.com/fc2blog/blog/blob/35c6d5cf6b87e5b80a5770b938620ad1a897666b/app/src/Model/CommentsModel.php#L165-L175

編集不可能かは、パスワードが設定されている（or、管理人のみ閲覧コメント）かどうかである。

「編集できない（≒パスワード未設定）」判定ができるならば、表示から編集リンクを消すべきではないか？
（同時に、パスワード欄下にでも「パスワードが未設定だと後で編集できません」と記載するとか）

あるいは、リダイレクトではなく、なんらか「パスワードが設定されておらず、変更は不可能である」と表示したほうが良いと思う。

**Comment by fc2dev** [comment]
@uzulla 
仰るとおり、編集ができないのであれば編集リンクを外していただくのが良いです。

**Comment by uzulla** [comment]
テンプレート if タグ系 `comment_edit`で制御できそう

**Comment by uzulla** [comment]
マージされましたのでクローズします。
