### ISSUE TITLE
flash messageのCSS不良？

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#129]
![image](https://user-images.githubusercontent.com/870716/91886118-d6846480-ecc3-11ea-8be5-20d2a904ba0c.png)
![image](https://user-images.githubusercontent.com/870716/91886147-de440900-ecc3-11ea-8435-95fb3219b207.png)

PC, SPともに、InfoのみFlash messageの幅が広いように見える。

https://github.com/fc2blog/blog/blob/42ca3203d5e0906409ffaabb9408f461a5c3c21d/public/css/admin_style.css#L220-L233

CSS上でもinfoのみ、marginが指定されている、これが意図したものなのかが不明。

**Comment by fc2dev** [comment]
@uzulla 
元々どのような意図があったのかは不明ですが、
不自然ではあると思います。
flash-message-infoから
margin : 0 0 15px; だけ外していただければ幸いです。

**Comment by uzulla** [comment]
#168 にて対応したためクローズ
