### ISSUE TITLE
スマホの投稿画面において、画像選択画面が閉じにくい。

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#132]
スマホのエントリ編集画面で、メディア（画像）を追加するダイアログが開いた際、ダイアログを閉じるボタンがないので、画面いっぱいとなり、閉じる方法が少々分かりづらい状態です。

実用上はダイアログから数ピクセル見える背景をタップか、「選択なし」の状態でadd ボタンで閉じることができます。

![貼り付けた画像_2020_09_04_15_34](https://user-images.githubusercontent.com/870716/92207876-00f14000-eec5-11ea-824f-3ca280997c6f.png)

(PCも、返信画面などでEscを押すしかない？）

**Comment by fc2dev** [comment]
@uzulla 
恐れ入りますが、現在デザイナーの割り当てがないため
現在ある素材で「閉じるボタン」をこの画面に追加いただく他ないと思います。
閉じるボタンは追加いただいて問題ありません。

**Comment by uzulla** [comment]
![image](https://user-images.githubusercontent.com/870716/101407654-877f4880-391e-11eb-92ce-ff89d68885ab.png)
![image](https://user-images.githubusercontent.com/870716/101407682-9239dd80-391e-11eb-8eaa-654524fa17df.png)

別件の画像リンク修正によって治った模様（おそらく #158 ）よってクローズします。
