### ISSUE TITLE
テンプレート検索、プラグイン検索でページャーが正しく動作していない？

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#135]
TBD

## テンプレート検索
![image](https://user-images.githubusercontent.com/870716/92297651-96034000-ef7c-11ea-9103-7b3c3d95443e.png)

## プラグイン検索
![image](https://user-images.githubusercontent.com/870716/92321784-beb43400-f067-11ea-85c1-c87f3fc22791.png)

**Comment by fc2dev** [comment]
@uzulla 
本件、不具合です。修正をお願いいたします。
