### ISSUE TITLE
不足しているタグ（topentry_enc_*)をOSS版にも実装する

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#146]
以下タグについて、変数（たとえば`$comment['trip']`）が生成される箇所（コード）を特定できない。
つまり現在も有効なタグなのか不明。

```
  '<%comment_trip>'      => '<?php if(isset($comment[\'trip\'])) echo $comment[\'trip\']; ?>',
  '<%topentry_enc_title>'          => '<?php if(isset($entry[\'enc_title\'])) echo $entry[\'enc_title\']; ?>',
  '<%topentry_enc_utftitle>'       => '<?php if(isset($entry[\'enc_utftitle\'])) echo $entry[\'enc_utftitle\']; ?>',
  '<%topentry_enc_link>'           => '<?php if(isset($entry[\'enc_link\'])) echo $entry[\'enc_link\']; ?>',
```

**Comment by fc2dev** [comment]
@uzulla
comment_tripはコメントのトリップ(投稿時に入力したパスワードに応じて8桁の英数字が生成)機能に関連するものです。
オープンソース版で実装されていないために、設定されていない配列にアクセスされてしまっています。
トリップ生成に使うseedをブログごとに動的に生成する形にしていただき、トリップを生成いただく様にすることで
互換性のある機能を提供いただければと考えています。

topentry_enc_title, topentry_enc_utftitleはURLエンコードしたタイトルを表示するための変数です。
topentry_enc_linkはURLエンコード化したエントリーURLを表示するための変数です。

ソーシャルブックマークボタンを設置したり、
ブログランキングへ参加する際に、ブログのURLやタイトルを通知するために主に使われている様子です。

**Comment by uzulla** [comment]
@fc2dev 

> トリップ生成に使うseedをブログごとに動的に生成する形にしていただき、トリップを生成いただく様にすることで互換性のある機能を提供いただければと考えています。

 なるほど了解です。互換性というのは、機能的なお話でよいでしょうか？（つまりOSS版と本家で入力値とハッシュ値の互換性がなくてよいでしょうか？）

また、tripを「割られない」ためのハッシュ強度についてなにか指定はありますか？（md5の先頭n文字でよい、sha256をsalt付きストレッチ100回でフルレングスがよい、など）

> topentry_enc_title, topentry_enc_utftitleはURLエンコードしたタイトルを表示するための変数です。
> topentry_enc_linkはURLエンコード化したエントリーURLを表示するための変数です。
> ソーシャルブックマークボタンを設置したり、ブログランキングへ参加する際に、ブログのURLやタイトルを通知するために主に使われている様子です。

これらは了解です。
そのようなデータを追加すればよいということですね。

**Comment by fc2dev** [comment]
機能的に互換性を保てれば問題ありません。

トリップ機能として使われているというよりは、特定の人（管理者、特定ユーザー）のコメントをCSSで表示を分ける
ユースケースで使っている様です。
ですので、
　・CSSで利用可能な文字種に限定する
　・文字数は8文字に限定する必要はない（一方で生成されたハッシュ値をfull lengthで取得する必要性まではない）
　・md5やsha1など推奨されないハッシュ関数は一応使わない
　・ストレッチ回数は具体的な希望はなく、やるとしても数回で十分と考えている
が最低限実現いただきたい内容です。

**Comment by uzulla** [comment]
表題の通り、 `topentry_enc_*`を対応したためクローズ。
トリップは別ISSUE #152
