### ISSUE TITLE
ユーザー側画面のデフォルトテンプレートで言語切替機能が提供されていない

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#162]
日英テンプレートのテスト時にcookieやConfigを書き換えてテストしていましたが、ユーザー側画面で言語切替をするルートが

- コメント編集画面
- 404画面

のヘッダー（`view/layout/default.php`) に存在しますが、通常画面からだと切り替え方法がみつかりませんでした。

また、初回アクセス時（未設定時)にAccept Languageヘッダによる自動判定などもないようでした。

~## 質問~

~ユーザー側の画面は「言語が切り替えできない」ように設計されていますでしょうか？~
~（Configを主としてあつかい、変更できること自体がイレギュラーでしょうか？）~
(上記当初記載しておりましたが、そうではなさそうなので、取り下げます)

以下の修正を提案します。

## 修正提案１、なんらか、かんたんにlangを指定できるように

「言語切り替え」プラグインなどをつくるか、単純に、パラメタに`lang=en`がある場合などに、前処理でCookieのlangを書き換えるのが良いのかなと思っております。

（ユーザーが単純に「英語で表示」リンクを作れる）

あるいは、langはCookieに保持されておりますので、非httponly属性のCookieで保持し、JSできりかえてもよいかと思います。

（同時に、Captchaの日本語/非日本語モードの切替はCookieを優先参照するように変更します #160 ）

## 修正提案２、「cookie未指定時に」Accept Languageを参照する

（現在の実装においては、Configの設定がデフォルトとなっているが）
日本語と英語のみなので、ブラウザの設定言語がja以外が上なら、enにすると良いかと思われます。

**Comment by fc2dev** [comment]
@uzulla 
1. langの指定がある場合は、その値を尊重しCookieをセット
2. 指定がない場合はAccept Languageを参照しその言語にする
3. 指定した言語が存在しない場合は、英語版を利用する
英語版の提供がない場合は、デフォルトの言語を利用する
の方針で行っていただければと考えています。

**Comment by uzulla** [comment]
マージされましたのでクローズします。
