### ISSUE TITLE
fc2 templateタグのI18n対応漏れ

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#164]
https://github.com/fc2blog/blog/blob/d81f0b3863a660b17ebb372ff859f13e6953eea8/app/config/fc2_template.php#L525-L544
https://github.com/fc2blog/blog/blob/d81f0b3863a660b17ebb372ff859f13e6953eea8/app/config/fc2_template.php#L144-L163

**Comment by fc2dev** [comment]
@uzulla 

ブログ側の英語を参考に入れていただくと良いと思います。
http://fc2manuals.blog.fc2.com/

**Comment by uzulla** [comment]
マージありがとうございました、クローズします。
