### ISSUE TITLE
/app/view/user/blogs/index.php テンプレートへの到達経路が不明

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#166]
ユーザー側ページのBlogsController::index アクションに対応するであろうテンプレートが存在するが、

https://github.com/fc2blog/blog/blob/18f7f85fbf31bcb19cfdefd835f295eac4793721/app/view/user/blogs/index.php#L1-L12

現在のOSS版では、「blogの一覧」はなく、トップアクセス時にランダムにリダイレクトするようになっている

https://github.com/fc2blog/blog/blob/2e08ae8fc4ec71aa2a7ccedb8fe77701ee1f4863/app/src/Web/Controller/User/BlogsController.php#L17-L25

そのため、`/app/view/user/blogs/index.php`へのアクセス経路が不明。不要であれば削除したい。

（あるいは将来的な復活が想定されている？）

**Comment by fc2dev** [comment]
@uzulla 
ランダムにアクセスさせる理由はなく、
何も想定をしていないので、削除していただいて問題ありません。

**Comment by uzulla** [comment]
削除がマージされましたのでクローズします。
