### ISSUE TITLE
管理画面 スマホにおいてトップの「未読コメントがあります」リンク先が記事一覧

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#170]
スマホにおいてトップの「未読コメントがあります」リンク先が記事一覧になっている
![image](https://user-images.githubusercontent.com/870716/97415599-ce097c80-1948-11eb-86f8-e018cec53003.png)

コメント一覧へリンクすべきだと思われる。
![image](https://user-images.githubusercontent.com/870716/97415732-ee393b80-1948-11eb-89c4-80cf078bcbe1.png)

さらにいえば、「未読」かつ「公開状態」が未指定な状態が正しいとおもうが
![image](https://user-images.githubusercontent.com/870716/97415922-217bca80-1949-11eb-98ac-3bb5f619ca2c.png)

## NOTE
SPは、この検索条件が虫眼鏡をおしておかないと隠れてしまうので分かりづらい
![image](https://user-images.githubusercontent.com/870716/97416008-3eb09900-1949-11eb-9e50-0de8f2f242d0.png)

**Comment by fc2dev** [comment]
・未読コメント　→　コメント一覧へリンクするようにお願いしたいです。

**Comment by uzulla** [comment]
マージありがとうございました、クローズします。
