### ISSUE TITLE
インストーラーの挙動改善

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#199]
配布ファイルの作成中に気づいた点について

- Mysql接続チェックと同時に、そのDBが存在するか（create databaseされているか）チェックしたほうがよい（権限があり、DBがない場合に500になってしまう）
- <s>パーミッションエラーについて、chmodが可能なら777と修正してしまったほうが早いのではないか？</s> 手元の開発環境特有の問題だった
  - <s>suexec環境やGROUP許可で許される特別なケースを除けば、777にしてしまうことになるだろうから</s>
  - <s>注意文は書いたほうが良さそう</s>
- <s>saltについて、現状自分で記入せよとしているが、Configを生成してしまったほうが早いのではないか？</s> 不要になった

**Comment by fc2dev** [comment]
1 Mysqlについては、databaseの存在確認をしてから後続の処理を行う
2 パーミッションエラーについては、chmodでパーミッションの変更が可能なケースについては
変更をする。
3 saltはインストーラーが別ファイルに書き込むようにする
ようにしていただいて問題ありません。

**Comment by uzulla** [comment]
一部の挙動は修正が不要だったのでとりさげました。

**Comment by uzulla** [comment]
マージいただいたので、クローズいたします。
