### ISSUE TITLE
captchaの数字がとても左よりになる

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#200]
- ![image](https://user-images.githubusercontent.com/870716/103461172-bcd15780-4d5f-11eb-8d51-54d86fa3a594.png)
- ![image](https://user-images.githubusercontent.com/870716/103461186-d07cbe00-4d5f-11eb-9803-2ccaab91955c.png)
- ![image](https://user-images.githubusercontent.com/870716/103461208-0457e380-4d60-11eb-9d4c-4d18c3d3dcfe.png)

頻繁に(1/5〜1/10くらい？)絶対に読めないタイプの画像が生まれるので、多少パラメタをいじって左に余白を作って良いのではないか？
（もちろん画像再生成をおせばよいので、これがよい塩梅という想定なのかもしれませんが）

**Comment by fc2dev** [comment]
Captchaが何桁か利用者が知ることはないので、左に寄りすぎるのであれば、
余白を入れるようにお願いしたいです。

**Comment by uzulla** [comment]
マージいただいたので、クローズいたします。
