### ISSUE TITLE
RSS機能がない

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#206]
テンプレートには以下のようにあるが、実際には動作しない。

```
<link rel="alternate" type="application/rss+xml" href="/testblog2/?xml" title="RSS" />
```

元々OSS版には未実装だが、テンプレートにあるので実装されているように見えているのだと思われる。

RSS、あるいはATOMを実装したい

## NOTE

- 「お知らせ」機能で引く先を検討しているが、RSSで実現できないだろうかと考えている（GitHub Pagesでもよいが）

**Comment by fc2dev** [comment]
RSSは未実装とのことです。
サンプル
https://fc2information.blog.fc2.com/?xml

機能を本体に合わせるため、実装をお願いしたいです。

**Comment by uzulla** [comment]
サンプル拝見しました、RSS1.0

**Comment by fc2dev** [comment]
RSS2.0にてお願い致します。

**Comment by uzulla** [comment]
マージいただいたので、クローズいたします。
