### ISSUE TITLE
blogs.blog_passwordをハッシュ化

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#207]
https://github.com/fc2blog/blog/blob/1459dc92649325946678371715f096e4588e6f8d/app/src/Web/Controller/User/EntriesController.php#L735

通常パスワードを平文でもつべきではないが、管理画面上でも平文で表示しており、これは利便性としてこのようにしたいということでよいか？

![image](https://user-images.githubusercontent.com/870716/104797740-ba610a00-5803-11eb-8b0e-0fd892fde6da.png)

**Comment by fc2dev** [comment]
パスワードを平文で保存することは現在は許容しておらず、平文をどうしても保管する（復号しないといけない）場合は
エンベロープ暗号化を利用することを必須としています。
キーの保管方法の問題が出るため、現行の使用を維持することは難しいかと思いますので、
ハッシュ値として保存を行うよう改修していただいて構いません。

**Comment by uzulla** [comment]
実装のため、タイトルを変更しました。

@fc2dev 

実装についてですが、

- ハッシュ化するとここからはパスワードは確認できなくなります。
- パスワード設定済みの状態においても、この画面を表示時は「ブログの閲覧パスワード」は空欄化し、横に「設定済み（あるいは『未設定』）、変更する場合は記入してください」的なテキストを記載するような形で実装すればよろしいでしょうか？
- この「ブログの閲覧パスワード」はブログの公開設定の非公開と連動しているようにおもえます※。よってこのパスワードを「空文字」に変更できる必要性はないかとおもいますが、「空文字（≒削除）」するケースは必要でしょうか？（パスワードを削除（≒空文字）するボタンをおいたほうが良いでしょうか？）

※ 以下のコードなどをみるかぎり、ブログの公開設定が「公開」であるかぎり、`blog_password`の出番がないのかなとおもっています。

https://github.com/fc2blog/blog/blob/b6be05d445e2442c9c3fc9e4ddead16c3d9fb243/app/src/Web/Controller/User/EntriesController.php#L61-L70

https://github.com/fc2blog/blog/blob/b6be05d445e2442c9c3fc9e4ddead16c3d9fb243/app/src/Web/Controller/User/EntriesController.php#L724-L728

**Comment by uzulla** [comment]
ご回答はいただけておりませんでしたが、一旦提案の方法で実装いたします

- ![image](https://user-images.githubusercontent.com/870716/106382841-83931280-6405-11eb-9563-d23e7f1c42b7.png)
- ![image](https://user-images.githubusercontent.com/870716/106382853-973e7900-6405-11eb-9410-f7cfaf2aed18.png)

**Comment by uzulla** [comment]
マージいただきましたのでクローズいたします。
