### ISSUE TITLE
デフォルトブログ機能（`/` アクセスで指定のブログが表示される機能）

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#211]
fc2blogはマルチテナント的な挙動のみとなっているが、自分のサーバーにインストールしてブログを運用する場合、シングルテナントモードがほしい。

- `http://example.jp/blog_name/` でなく
- `http://example.jp/` でブログを表示したい

> 現在`/`アクセス時はランダムなブログにリダイレクトしている

===

- [x] ルーターのリファクタリング
- [x] URL生成箇所の修正
- [x] テストおよびコードの対応

**Comment by fc2dev** [comment]
マルチテナントはそのままとし、「デフォルト」のブログを設定できる様にし、
/アクセス時は、デフォルトに設定されたブログを表示する形でいかがでしょうか？

**Comment by uzulla** [comment]
@fc2dev 

なるほど、ご検討ありがとうございます。
URL構造的に衝突があるかもしれないのでそこを調査しつつ実装してみたいと思います。

**Comment by uzulla** [comment]
> 「デフォルト」のブログを設定できる様にし、

![image](https://user-images.githubusercontent.com/870716/106402786-9ee63800-646e-11eb-8f6e-e8d8388c1bb3.png)

ぱっと考えると、この「ログイン後の表示ブログ」を用いることができそうだが、これは`users.login_blog_id`なので、ユーザー毎に発生してしまうのでつかうことができない。

![image](https://user-images.githubusercontent.com/870716/106402850-fe444800-646e-11eb-98df-f0b504b1a988.png)

よって「ブログ設定」の中に設置することが考えられる。「このブログをデフォルトにする」といったチェックを追加することが考えられる。
その上で、`blogs.is_default`みたいなbool or NULLなカラムをつくれば解決できそう。

あるいは、ブログ設定と同じ階層に「サイト設定」みたいなものを追加することも考えられる（が、ちょっと工数的に大変なので、前者で良いかなと思われる）

**Comment by uzulla** [comment]
管理画面側の対応について
![image](https://user-images.githubusercontent.com/870716/107738290-b7e1c980-6d49-11eb-8bd9-b473b287c1c9.png)

この画面で「デフォルトブログ」を選択させるのが一番一覧製が高くわかりやすいように思えてきた。

**Comment by uzulla** [comment]
管理画面以外は実装され、マージいただきましたので、クローズします。
（管理画面で、簡単に設定する機能は #230 に引き継ぎ）
