### ISSUE TITLE
MITライセンスとの不整合

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#22]
READMEの以下はMITライセンスと適合しないと思われます。

```
*Do not remove the link to FC2 in the template.
```

MITライセンスより抜粋

```
〜without limitation the rights to use, copy, modify, 〜
```

### 前提

以下のフッター表記のことだとかんがえておりますが、別のところを指しているとしたらご指摘ください。

![image](https://user-images.githubusercontent.com/870716/88159441-4379f880-cc48-11ea-9f7c-163bc8eac7bb.png)

## 解決手法

1. 上記の「修正に対する制限」の記述を削除する
2. 「特別な保護をしたいテンプレート」を分離し、そちらにはそのような独自の（すくなくともMITなどではない）ライセンスを適用する。

テンプレートを独立させる場合は、利便性を考えるとインストール時に自動的に展開されるようにするなどの実装が必要。
しかしなんらか"Generic" なテンプレートを添付しないと「MITで成り立つBlogシステム」なのか疑問がのこる。

**Comment by fc2dev** [comment]
1で対応を行なっております。

**Comment by uzulla** [comment]
ありがとうございます、クローズいたします。
