### ISSUE TITLE
サイト内リンクにおいて、エントリ個別ページのURLを blog-entry-{id}.html 形式に変更

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#221]
SEO対策などのためと思われるが、エントリ個別ページ（記事毎のページ）

`http://localhost:8080/testblog2/blog-entry-3.html`

といった形式のURLがサポートされているが、ページ遷移で到達できるエントリ個別ページは

`http://localhost:8080/testblog2/?no=3`

といった形式になっている、これは問題ないか？

***

- [x] `App::userURL`
- [-] [ルーター問題](https://github.com/fc2blog/blog/issues/221#issuecomment-772951263) （Spでしかつかわれないモードなので、特に問題にする必要はなさそう）

**Comment by fc2dev** [comment]
URLの一貫性を保つためにも、blog-entry-{id}.html形式に統一いただいた方が良いかと思います。

**Comment by uzulla** [comment]
承知しました、作業用にISSUEタイトルを変更いたします。

**Comment by uzulla** [comment]
単純置換だとルーターで問題
![image](https://user-images.githubusercontent.com/870716/106830870-3eefcb80-66d2-11eb-9655-850f7acd8735.png)

**Comment by uzulla** [comment]
マージいただきましたので、クローズいたします。
