### ISSUE TITLE
管理画面におけるサポートブラウザの範囲

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#235]
@fc2dev 訪問者側のブラウザサポートはテンプレート次第ですが、管理画面について「基本的に」サポートしたいブラウザ範囲はどうなりますでしょうか？

具体的には管理画面のJSを静的解析ツールをかけてリファクタリングをしていきたく、ES6相当程度まではあげられればと考えています。JSやCSS Hackなども不要なものは削除し、古いjQueryのバージョンもあげたいと思います。

問題と考えているのは、IE11と非ChromeのEdgeのサポートになります。

参考： https://kangax.github.io/compat-table/es6/

問題がなければ、モダンな(Chromium)Edge, Chrome, Safari, などの最近のバージョン絞り込めればと考えています。

**Comment by uzulla** [comment]
一部、IE10（11では動作しない）ハックなどがあり、これらもサポートブラウザ範囲がきまれば削除したいと思います。

https://github.com/fc2blog/blog/blob/16fbabb09cb99cd9c492814e3210002c198fbad4/public/js/admin/entry_editor.js#L103

**Comment by fc2dev** [comment]
@uzulla 

https://help.fc2.com/requirements
この推奨環境に準じた対応で構いません。
IEについてはオフィシャルのサポートが切られていることもあり、
サポート対象からは切り離していただいて構いません。

**Comment by uzulla** [comment]
承知しました、JSのリファクタや、適宜必要なタイミングでIE系のハックを外すなどしていきます。
