### ISSUE TITLE
管理画面ファイル管理で、ファイル削除UIがリンク（GET）で実装されている

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#236]
![image](https://user-images.githubusercontent.com/870716/108140817-de1ab700-7105-11eb-8db1-39634443f41e.png)
![image](https://user-images.githubusercontent.com/870716/108140867-f7236800-7105-11eb-83bd-6c3d23cb816a.png)

- 先読み機能やプレビュー機能で事実上アクセスされた場合、意図せぬ削除が発生する
- POST、あるいはJSに変更したい

**Comment by fc2dev** [comment]
POSTへの変更をお願いしたいです。

**Comment by uzulla** [comment]
マージいただきましたので、クローズいたします。
