### ISSUE TITLE
http→https、https→http 強制リダイレクトおよび内部リンク時schema指定機能

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#25]
#17 より

## 概要

ブログ設定にて

- 「SSL設定」の「有効」「無効」スイッチを設置する
- 有効だと
  - 内部的な該当ページへのリンクのSchemaをhttp、またはhttpsに設定する
  - 設定と異なるschemaでアクセスされた場合、リダイレクトする
    - https->httpもリダイレクトする
  - ステータスコード指定ができるとなお望ましい
- この設定はブログID毎に指定できる

## スイッチ差し込み場所

![image](https://user-images.githubusercontent.com/870716/88246532-c5643300-ccd5-11ea-98f1-2428b057516f.png)

## note

テンプレートに記載されているアセットなどのリンクURLにおけるschemaは特に変更されない。
あくまでも同一ブログシステム内での内部リンクでのみ作用する。

**Comment by uzulla** [comment]
@fc2dev 
https://github.com/fc2blog/blog/pull/27
でプルリクしました

**Comment by fc2dev** [comment]
@uzulla 
マージを行いました。
文言については特段問題なさそうです。

**Comment by uzulla** [comment]
ありがとうございます。一旦クローズさせていただきます。
なにかありましたらRe-openなどしていただければと思います。
