### ISSUE TITLE
管理画面、記事一覧テーブルの視認性改善

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#251]
![image](https://user-images.githubusercontent.com/870716/110111699-16074700-7df4-11eb-9bb2-70e3b95ad9b1.png)

タイトルが省略されるのが不便。本文もいかにも短いので活用しづらい、HTMLがでているのが不便に感じる。
タイトルや本文がもうすこし見えてほしい。HTMLは邪魔なのでhtml stripした後の文字列を使いたい。

## 案

- 案1：今のテーブル構造のまま、もう少し文字数を増やす。幅も調整する
- 案2：本文をけして、タイトルをフルで出す
- 案3：タイトル、本文を1つのセルにまとめて、二行表示にする
  - ただし、列タイトルが今ソートボタンなのでこれは活かす必要がある（が、本文やタイトルでソートは必要なのだろうか？）

## ついでの作業として

- 状態、コメントカラムがセンタリングされていないのが少々きもちわるいのでセンタリングする

**Comment by fc2dev** [comment]
案３で進めていただいて問題ありません。
タイトルや本文でのソートはあまり意味をなさないと考えているので
省略するか、タイトルでのソートにしていただくかどちらかで構いません。

**Comment by uzulla** [comment]
マージいただきましたので、クローズいたします。
