### ISSUE TITLE
ログイン試行アタックに対する軽微な軽減策

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#266]
現状特に特別な対処がされていないため、総当りが容易。
典型的な対処方法の一つとして、ログイン失敗時にはペナルティとして数秒のウェイトを入れたい。

## note

- 軽微な欠点として、特にMaxClientsが低いサーバーにおいてPHPプロセスを専有するタイプのDoSが通常より容易になる可能性がある
- 本質的にはcaptchaや、MFAを導入したいが、ライトユーザーにおいては利便性が損なわれる

**Comment by fc2dev** [comment]
ご提案のWaitの方式に加え、
アクセス元の制限（IPまたはGeoIPによる国単位のブロック）、
MFAの中でもメールアドレスへログイン用のリンク・認証コードを送る　方式を
用意いただくのが良いと思います。

**Comment by uzulla** [comment]
- アクセス元の制限（IPまたはGeoIPによる国単位のブロック）
- MFAの中でもメールアドレスへログイン用のリンク・認証コードを送る
については大きな作業となりそうですので、別途ISSUE化いたします。

**Comment by uzulla** [comment]
マージいただきましたので、クローズいたします。
