### ISSUE TITLE
パスワード再発行機能

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#267]
現状、ログインIDやパスワードを忘れた際にリカバリーする方法が用意されていない。
DB内のパスワードもハッシュ化されており、パスワードをよみとれない。そしてハッシュを作成するのに多少知識が必要。
ログインIDもメールアドレスではないので、一般的なメールによるリカバリができない

## 実装

- [x] パスワードリセット緊急ツールの提供
- [x] ログインIDにメールを利用し、一般的なウェブアプリと同様のパスワードリカバリプロセスを実装

**Comment by fc2dev** [comment]
ログインIDにメールを利用する　か　ログインIDにメールアドレスを紐づけられるようにしていただきたいです。
その上で、パスワードのリセットの実装を希望します。
利用しているサーバーの仕様でメールが適切にリレーされないケースも想定されるので、
パスワードのリセットのツールを別途用意いただくのが良さそうです。

**Comment by uzulla** [comment]
マージいただきましたので、クローズいたします。ありがとうございました。
