### ISSUE TITLE
管理画面のsig生成をログイン時に統一

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#277]
#246 #237 などでsigが想定しないタイミングで更新されたりするケースが多く存在し、特にajax系ではリトライ（ユーザーの誘導）が難しい状態となっています。

sigが更新されるタイミングはそれぞれのページを表示している場合に更新されております（なお、されていないページもある）。

sigの目的である（と、私が考える）CSRF対策としては、ログイン時ににのみsigを生成し、個々の操作ではsig更新しない形で十分ではないかと考えられますが、いかがでしょうか。 

勿論sigの寿命が伸びることでsig流出に対する安全性は低下しますが、sigが入手できる手段が何かある時点で別の問題があります。（たとえば、現状の一部メソッドの実装はGETなのでsigがアクセスログから拾えるとか、httpをつかっていてCookieが盗めるとか）

**Comment by fc2dev** [comment]
ログイン時に統一いただいて問題ありません。

**Comment by uzulla** [comment]
ありがとうございます、その方向で改修いたします。

**Comment by uzulla** [comment]
マージいただきましたのでクローズいたします。
