### ISSUE TITLE
Cookie周りの仕様の近代化改修

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#29]
現状のコードのCookie周りの仕様について、意見があります。
いまはかなり古い設計となっており、もっとモダン（セキュア）な設定にすべきかと思われます。

- cookieのdomainが指定されている
  - cookieのドメインは「指定しなければ」現在のホストになるので、十分です。
  - cookieのドメインが間違っていると、セッションが付与できません（そして、気づきづらい=>設置者が困る）
  - ワイルドカード的な活用をする「場合にのみ」、指定する意義はあるかと思いますが、基本は不要で必要な時に設定できる形が良いかと思います
- cookieにhttponly属性が付与されていません、つけるべきだと思います。（JSから触る必要な箇所がみつけられませんでした）
- cookieに明示的なsamesite指定が有りません、つけるべきだと思います。（いずれにせよ今後Laxが最低限になるので）
- https環境ならsecureを指定するべきです（httpsであるかどのように検知するかは議論の余地があります）
  - http,httpsデュアルスタックのサイトであったとしても、管理画面はhttps固定にするなどが必要ではないかと思います。（これは別のISSUEになりますが、公開URLがhttp・https両対応は良いとしても、管理画面はhttpsが利用可能なら必須とすべきと思います。）

### 現状のCookie名（キー名）設計について

`DOMAIN`設定からひっぱる形で、
`SESSION_DEFAULT_DOMAIN`
`COOKIE_DEFAULT_DOMAIN`
と2つにわかれているのもちょっとよくわかっておりません。
（過去の設計がこれを必要としていたのかもしれませんが、その理由が暗黙なので、普通にコードを読むと統一すべきように見えます）

実際、コード上でも統一されておらず、一部ではドメインを指定していないコードがあります。

https://github.com/fc2blog/blog/blob/5cef4f4d5255bd40ac96abb0c8d5e4ff2412ce4b/app/config/fc2_default_template.php#L38-L39

## 具体的な改修案

- domainをデフォルトでは外す
- samesite=lax指定する（できるなら、必要がでるまではstrict。Noneは必要がないなら避けるべきですし、https必須になるので）
- httponlyを付与する(JSでセッションのCookie値を参照する箇所はないかと思っております）

## note

```
// SESSIONのID名
$config['SESSION_NAME'] = 'dojima';
```

単なる好奇心(?)なのですが、dojimaとはなんでしょう？

**Comment by fc2dev** [comment]
@uzulla 
Cookieの仕様については、セキュリティスキャンのレポートにも上がっており、
変更をした方が良いと思います。

変更について確認をしていますので、お返事までもう少々お待ちください。

**Comment by fc2dev** [comment]
@uzulla 
本件、実装を進めていただきたいです。

**Comment by uzulla** [comment]
@fc2dev 

承知しました。
（お手数なのですが、Assigneesで私をアサインするなどしてもらえるとわかりやすいなと考えております。ご検討ください）

**Comment by uzulla** [comment]
@fc2blog

cookie周りは各種ブラウザの依存が多少あるので確認したいのですが、本ウェブアプリのクライアントにおける動作環境は決まっていますか？
動作保証をどうするかはさておき、目標とする範囲を知っておきたいです。

**Comment by uzulla** [comment]
https://github.com/fc2blog/blog/pull/35
一旦実装させていただきました。方向性がみえたらばまた修正できればと思います。

**Comment by uzulla** [comment]
#35 はマージされ、残作業となるJSは別ISSUEといたしましたので、クローズいたします。
