### ISSUE TITLE
管理画面ログイン認証でMFAを実装

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#292]
https://github.com/fc2blog/blog/issues/266#issuecomment-803456452 より引き継ぎ

- [x] MFA（他要素認証）としてメールアドレスへログイン用のリンク・認証コードを送る

> :heavy_check_mark: 本件の前に、ユーザーIDのメールアドレス化などが必要 

## note

- メールアドレス送信方式は不達や遅延でログインがしづらくなるため、個人的にはMFAとして一般的なTOTPの認証も選べるようにしたい。

**Comment by fc2dev** [comment]
メールアドレス送信方式に加えて、TOTPの認証も追加いただいて問題ありません。

**Comment by uzulla** [comment]
マージいたしましたのでクローズいたします。TOTPの実装は別途ISSUEを作成いたします。
