### ISSUE TITLE
FC2公式テンプレートAPIが接続元のIPによってはTimeout する

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#296]
`https://admin.blog.fc2.com/oss_api.php?action=template_search` エンドポイントにおいて、一部のIPアドレスからのアクセスを拒否している模様。
別のIPからでは正常に取得ができた。

- タイムアウトを「正常系」として扱う（エラー画面をなんらか適切にする）
- その後のリカバリー（代替）方法が想定できない
  - アクセス許可を増やす想定はありますでしょうか？
  - テストのIPは 150.95.9.42 からのアクセスとなります

![image](https://user-images.githubusercontent.com/870716/112713330-e8577e80-8f17-11eb-9892-502a9c606230.png)
![image](https://user-images.githubusercontent.com/870716/112713652-bb0bd000-8f19-11eb-91b8-6d90e30f25a7.png)

**Comment by fc2dev** [comment]
弊社のサーバーはミドルウェアレベルでアクセス制限を入れていることがあります。
その場合は、タイムアウトにさせずに何かしらのレスポンスコードを戻すようにしています。
ホスティング会社のIPからのアクセスやボットネットワークに感染しブラックリストになってしまったIPなどは
接続を拒否することがあります。
ですが、timed outにさせるようなことはないため、一旦インフラエンジニアに確認をします。
（ファイヤウォールレベルで拒否をしている可能性は否めません）

**Comment by fc2dev** [comment]
150.95.9.0/24のレンジから過去に大量のアクセスがあったようでブロックしていたようでした。
今は解除されていますので、再度お試しいただければと思います。

**Comment by uzulla** [comment]
さきほどテストし、問題なく通信ができることを確認いたしました。ご対応ありがとうございました！
本件クローズいたします。
