### ISSUE TITLE
PHP7化(対応まとめ)

### ISSUE THREAD

**Issue by ryonakaji** [fc2blog/blog#34]
# 概要
fc2blogのオープンソースのPHP7化対応を行った際の調査、対応、テストなどをまとめます。
現在PHPはバージョン5.2.17 or higher、MySQLはバージョン5.1 or higherで担保されていますが、PHP7.4.x(2020年7月時点の最新バージョン)以上で動くよう対応しました。
また、その対応による動作検証も合わせて行っております。

### 対象コード
https://github.com/fc2blog/blog

# 調査
### スクリプトによる該当箇所調査
php5.2.x->7.x.xの互換性調査として 『[PHP 7 Compatibility Checker 1.2.1](https://github.com/sstalle/php7cc/releases)』を用いてコード全体のチェックを行いました。

<スクリプト実行結果>
```
XXX-MacBook-Pro:task {name}$ php7cc.phar blog/

File: /Users/{name}/Desktop/task/blog/public/js/elrte/src/post.php
> Line 2: [Error] Removed function "set_magic_quotes_runtime" called
    set_magic_quotes_runtime(0);

Checked 75 files in 0.971 second
```
上記の通り、`set_magic_quotes_runtime`メソッドのみ引っかかりました。

### 手動による該当箇所調査
スクリプト実行では対応不可である最新バージョンの確認や、また万が一の対応漏れがないようにするため、手動でもphp5.2.x->php7.4.xまでの変更点全てを調査しました。
[fc2blogコード手動調査.pdf](https://github.com/ryonakaji/Issue/files/4999138/fc2blog.pdf)
※弊社のコンフルにまとめてあるものをPDFとしてexportしたため、多少の表示崩れがありますことご留意ください。

### スクリプト実行と手動調査による調査結果
下記3点の修正が必要ということが判明
1. 波括弧を使った、配列や文字列のオフセットへのアクセス 
  - https://www.php.net/manual/ja/migration74.deprecated.php
2. countable ではない型をカウントしたときの警告
  - https://www.php.net/manual/ja/migration72.incompatible.php
3. set_magic_quotes_runtimeメソッドの廃止
  - https://www.php.net/manual/ja/function.set-magic-quotes-runtime.php

# 実装
### 実装内容(diff)
既にmasterブランチにマージ済みであるため、forkした弊社のリポジトリにおけるプルリクエストに加え、diffをテキスト形式でも添付させていただきます。
https://github.com/samoslink001/blog/pull/1
[gitdiff.txt](https://github.com/ryonakaji/Issue/files/5004377/gitdiff.txt)

# テスト
### 結合テスト
対象ページのテストは全て通過しました。
何箇所か結果が x となっている箇所がありますが、こちらがお伝え済みの既存バグが原因のものです。
[fc2blog_php7_結合テスト.xlsx](https://github.com/ryonakaji/Issue/files/4999433/fc2blog_php7_.xlsx)

### 性能テスト
* 1秒間に121.4回読み込みと実行が可能なので実用性に問題無し
* 1度の読み込みと実行が0.008233秒で処理が完了するため問題無し
[fc2blog性能確認テスト.pdf](https://github.com/ryonakaji/Issue/files/4999410/fc2blog.pdf)

# その他資料
### 対応スケジュール
[fc2blog_PHP7化対応スケジュール表.xlsx](https://github.com/ryonakaji/Issue/files/4999398/fc2blog_PHP7.xlsx)

**Comment by fc2dev** [comment]
確認いたしました。ありがとうございました。
