### ISSUE TITLE
コメント投稿確認画面で、head titleタグが「サイト名」固定になっている

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#43]
https://github.com/fc2blog/blog/blob/13393f90c035b523b05a323b2628a5576e641c41/app/view/user/layouts/default.html#L10

![image](https://user-images.githubusercontent.com/870716/89506066-7ce46380-d805-11ea-8d7b-f3311a501369.png)

**Comment by fc2dev** [comment]
@uzulla 
変数を適切に入れていないと思います。
お手隙の時に修正をお願いいたします。

**Comment by uzulla** [comment]
作業ブランチがマージされましたので、クローズいたします。
