### ISSUE TITLE
コメント削除が機能しない?

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#44]
![貼り付けた画像_2020_08_06_18_03](https://user-images.githubusercontent.com/870716/89513218-3dbb1000-d80f-11ea-82f1-e74c608813f0.png)

この削除をクリックすると、

![image](https://user-images.githubusercontent.com/870716/89513278-53303a00-d80f-11ea-8f52-19451b689922.png)

編集画面へ遷移してしまう

**Comment by fc2dev** [comment]
@uzulla 
バグの様子です。お手隙の時に修正をお願いいたします。

**Comment by uzulla** [comment]
@fc2dev 

PRから参照しておらずすみません、以下で対応済みです。

#48

**Comment by uzulla** [comment]
作業ブランチがマージされましたので、クローズいたします。
