### ISSUE TITLE
archives.htmlでタイトルがおかしい？

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#45]
![image](https://user-images.githubusercontent.com/870716/89530171-ffcae580-d828-11ea-98d1-42f532845491.png)

` - testblog2`となっているが`記事一覧 - testblog2`などとなるのがただしいのではないか？

**Comment by fc2dev** [comment]
@uzulla 
ご指摘の通り、記事一覧　と表示されるのが正しいです。

**Comment by uzulla** [comment]
作業ブランチがマージされましたので、クローズいたします。
