### ISSUE TITLE
/admin/install.php によるブログインストール後、ロックファイルを生成してインストーラーを無効化する

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#57]
![image](https://user-images.githubusercontent.com/870716/89706473-f8c6e300-d9a0-11ea-911f-cf9218193922.png)

`/admin/install.php` のインストール後のメッセージに「またadmin/install.phpは不要ですので削除してください」と表示されますが、お願いは多くの場合してもらえませんし、削除したほうがよければ削除するロジックをいれてもよいかと思います。

また、「インストール後に再度操作してもなにもおこらない」のはコードをよむとわかりますが、画面上は「再インストール（初期化）」ができるように見えるので、そこも多少錯誤を生むかなと思われます。
（実際には二度三度と実行しても、不活性化（チェックをして、問題がなければなにもしない）されています）

しかしながら、DB接続情報が表示されてしまうのは少々問題かと思います。

![image](https://user-images.githubusercontent.com/870716/89706436-9837a600-d9a0-11ea-9272-4e12be984d37.png)

## 対応策の検討

将来的に自動アップデートを入れることを考えると、配布ファイルが固定されない（減ったりする）のは不便かなと考えております。

すでに「インストール済みかどうか」を確認するロジックは存在しているので、アクセス時に「インストール済みです」と表示してしまうように挙動を変更するのはいかがでしょうか。

ご検討いただければ幸いです。

## 対応策

[こちらにて方針を頂いた](https://github.com/fc2blog/blog/pull/53#issuecomment-673882480)
ロックファイルを実装する

**Comment by fc2dev** [comment]
@uzulla 
ファイル自体を削除するのではなく、インストール済みであることを表示し
スクリプト自体が実行されない様にしていただきたいです。よろしくお願いします。

**Comment by uzulla** [comment]
#53 より

```
admin/installer.phpを利用後「削除してください」というのはいかにも面倒なので、インストールがおわったら自動的にうごかなくする機能があれば便利だと思われる。
（ID/PASSを忘れた時のレスキュー用途かとおもっていたが、特にそういうことはないようなので）

installer.phpを削除してしまう（必要なら、再度アップロードさせる）
「インストール済み」を示すような…
app以下になにかロックファイルを作る（削除すれば、また動く）
```

[ご回答いただいたので](https://github.com/fc2blog/blog/pull/53#issuecomment-673882480)ロックファイルの実装をする。

**Comment by uzulla** [comment]
マージされましたので、クローズいたします、ありがとうございました！
