### ISSUE TITLE
favicon.ico がないことによる無駄なリクエストの発生

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#58]
現在`/favicon.ico`がないことで、正常なアクセスであってもブラウザから複数回の無駄なアクセスが発生しています。

存在しないfaviconへのアクセスは（404的な挙動で）`/`にリダイレクトされ、そこからさらに`/{なんらかのブログ}/`にリダイレクトされています。

## 提案

- faviconを作成し、追加する
- 404相当のルートを作成する
- `.htaccess`に記述してApacheで404を返す

上から順によいと思います、いかがでしょうか。ご検討ください。

**Comment by fc2dev** [comment]
@uzulla 
権利関係の問題から、弊社のFaviconをこのレポジトリに同封させることができません。
https://static.fc2.com/share/image/favicon.ico 
を参照する形で利用ください。

**Comment by uzulla** [comment]
@fc2dev 

承知しました。テンプレ修正ということになりますね。

ただ、それと同時に、メタタグでfaviconの位置指定が完全にできていないページにくるとアクセスはやはり発生してしまうので、htaccessか、アプリ側かどちらかで、favicon.icoをブロックする処理は入れたいと思います。

**Comment by uzulla** [comment]
マージありがとうございました！！
