### ISSUE TITLE
app/shell/cron.php、Cronのドキュメントにつきまして

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#66]
@fc2dev 

Cronで`EntriesController::updateOpenStatus`などが実行されることを期待されているとおもいますが、このあたり想定する設定のドキュメントはございますでしょうか？

コードを読んで類推はできておりますが、Crontabにどのように設定されるのかよろしければお教えいただけますと幸いです。

**Comment by uzulla** [comment]
@fc2dev 

このあたり、いまいち正しい動作をするものかわかっておりません。

おそらく、以下のような実行を想定しているのかなと考えております。

```
php ./cron.php Entries updateOpenStatus
```

古いコミットにもどしてみても、正しい動作がしない？ようでした。

また、コード的にもinitial commit時（ f6dce4b84aa28dff54bee2ae8452e25a59143b31 コミットID）において

https://github.com/fc2blog/blog/blob/f9b41646e8d91f58b7283b92012516930b17510f/app/shell/cron.php#L15

で呼ばれる`process`メソッドの定義が無い？ように見えます。

また、

https://github.com/fc2blog/blog/blob/f9b41646e8d91f58b7283b92012516930b17510f/app/shell/cron.php#L12

でよばれる`new $className();`は（仮に）`EntriesController => CronController => AppController => Controller`とたどると

https://github.com/fc2blog/blog/blob/f9b41646e8d91f58b7283b92012516930b17510f/app/core/controller.php#L21

で、コンストラクタは引数`$method`を要求しておりました（そして、それは子孫で特に上書きされておらず）

なにか実行方法がまちがっているのか、もともとの挙動なのかと判断しかねております。

よろしくお願いいたします。

**Comment by fc2dev** [comment]
@uzulla 
最後のコミットから年数が経過しており、
本プロジェクトについてのドキュメントや過去の担当者にヒヤリングすることは難しい状態のため、
Githubに置いてあるものが全てのアセットです。

Cronでは公開日時を指定した「予約投稿」や公開期間を限定した「期間限定投稿」の処理を期待している様子です。
しかしながらReadmeのインストールの手順にはCronについて言及はないものの、
記事を表示するたびに、updateReservationとupdateLimited を実行している様に見受けられます。

このCronを実装しようとしたものの、実装はしていない残骸なのだと考えられます。
crontabを設定することを前提とするのは、多種多様な利用環境が想定されることや
利用者様の利便性を考えると難しいと考えています。
最後に予約投稿や期間限定投稿の処理が行われた時間を記録しておき、一定時間(例えば10分)は
該当の処理を実行しない様にするのがOSS版では望ましい様に思います。

表示の際に当該処理を実行したくない人は、Crontabでご推察いただいた様な記述を入れていただく形で
良いのではないかと考えています。

**Comment by uzulla** [comment]
@fc2dev 

> しかしながらReadmeのインストールの手順にはCronについて言及はないものの、
> 記事を表示するたびに、updateReservationとupdateLimited を実行している様に見受けられます。

なるほど、ぱっときづきませんでした指摘ありがとうございます。
https://github.com/fc2blog/blog/blob/f252713552f5baefabafb47b49c68021e24f743e/app/src/Web/Controller/User/EntriesController.php#L58
この箇所ですね。

> このCronを実装しようとしたものの、実装はしていない残骸なのだと考えられます。

ということであれば

- うごいていないのだから、一旦このあたりのコードは削除
- Cron機能を作りきる

どちらがよろしいでしょうか？

> 最後に予約投稿や期間限定投稿の処理が行われた時間を記録しておき、一定時間(例えば10分)は
> 該当の処理を実行しない様にするのがOSS版では望ましい様に思います。
>表示の際に当該処理を実行したくない人は、Crontabでご推察いただいた様な記述を入れていただく形で
> 良いのではないかと考えています。

こちらもなるほどですが、「一定時間実行しない」ためのチェック処理がはいるならば、今のように都度チェックしても（IndexがきいていてDBサイズが極端に大きくなければ）十分速いかなと思われます。

なので、これはこった工夫をせず、このままの設計で良いのではないかと思います。

**Comment by uzulla** [comment]
@fc2dev 

一旦（動作しない）Cron処理（コントローラ周り）は削除して（updateReservationとupdateLimited はもちろん維持します）、必要な時に再度つくる、ということにしたいと思いますがいかがでしょうか。
（現状のCronはWebのコントローラを流用しているので、あまりCliに適した設計になっておりませんでしたので）

**Comment by uzulla** [comment]
#93 にて、一旦Cron周りのコードは削り込みをおこないました。
ロジック自体はのこされているので、必要であれば別途Cron用のCliを作成します。その場合起票ください。

ありがとうございました、クローズいたします。
