### ISSUE TITLE
提案 テンプレートリビルドコマンドの実装

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#73]
現在毎回`fc2_default_template.php`修正後に管理画面からコピペして更新していますが、自動テスト時に失敗することがあります。
解決のために、`\Fc2blog\Web\Controller\Admin\BlogTemplatesController::apply`相当の処理をCliで受け付けるコマンドを作れればと考えています。

当座は開発・テスト用ですが、将来的にはテンプレートバージョンアップで同様の機能が必要になるかと考えています。

## 概要

おおまかにいえば、以下のような事がしたいと考えています。（もうすこしオプションは増減すると考えています）

```
$ update-template -blogid my_blog_id -templateid 1 -target pc -type template -input ./fc2_default_template.php
$ update-template -blogid my_blog_id -templateid 1 -target sp -type css -input ./fc2_default_css_sp.php
```

## 想定利用シーン

- テスト実行前のテンプレートの更新（ファイルからの最新化）の自動化

(作業時間 3h

**Comment by fc2dev** [comment]
@uzulla 
実装をお願いいたします。

**Comment by uzulla** [comment]
マージされましたので、クローズいたします、ありがとうございました！
