### ISSUE TITLE
提案： テストのしやすさを高めるために、コントローラー設計を変更し、リクエスト等の「状態」の引数化

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#76]
テストを増やしてほしいというご依頼から、現在は管理画面のテストを増やすために各種調査や検討をおこなっておりますが、いくつか課題があると感じております。

## 現状

まず、現在の設計においてコントローラーは以下のように推移します。

`app/src/Web/Controller/Admin/UsersController.php`において

- （初期化）
- `beforeFilter()` → シングルトンから情報をとりだして認証などを実行したり、シングルトン内のデータを加工など
- `${ルータで解決された}method();` → コントローラ実行、返り値はテンプレートファイル名のみ、データはシングルトンから取り出し、保存
- `afterFilter()` → 現在は空、将来用？
- `layout($template)` → 内部で`extract()`をつかって、一方向なレンダリング（これは別でIssueを立てます）

https://github.com/fc2blog/blog/blob/b342886aa89e3a28318f538a536340e6853d209d/app/src/Web/Controller/Controller.php#L47-L60

この設計はユニットテストがしやすくありません。

（ユニットテストができないとE2Eテストにならざるをえませんが、E2Eテストは時間がかかり、なおかつ確認するのはHTML解釈から行う必要があるので、工数コストが高すぎます）

## 状態が複数あり（Request、Config、Controller->data）、シングルトンの多用がきびしい

現状、Filterやmethod、レンダラそれぞれでシングルトン（≒グローバル変数）のRequestやConfigを内部で読み書きしたり、コントローラの`$this->data`の読み書きする設計となっております。（テンプレートから、直でConfigをコールしたりもしている）

```
// 例、Admin/BlogsControllerより、引数でなく、内部でシングルトンから読み込み
  public function create()
  {
    $request = Request::getInstance(); 

```

これは

- Configという、一見不変に見えるものにも状態が持たれている
  - （個人的には、Configは便利配列をめざしすぎており、構造体的なクラスに変更したほうが良いとおもいますが、それは一旦さておき）
- 複数箇所でデータの受け渡しがされている、どこを監視すべきかわかりづらい
- 初期化しづらい（RequestやConfigはシングルトン設計になっている）

https://github.com/fc2blog/blog/blob/f50cad6c2ee30607470ff874979c9bce9af4649f/app/src/Web/Request.php#L43-L49

という所でユニットテスト作成がしづらい状態です。

テストのないPHPアプリでは問題になりませんが（正直、シングルトンは実装においては楽で、メリット大だったのだろうなと思います）、ユニットテストでは同一の実行中で多数の仮想的なリクエストを処理できることが望ましく、状態を安全にリセットできないと厳しかったり、リクエストが明示であったり、複製できたほうが便利です。

よって、テストのためには、メソッドやフィルタは状態を渡して状態を返してもらうように（グローバル変数的なものを避ける）再設計すべきかと思います。

- Requestはシングルトンをやめて、都度生成、引数渡しにする
- Configで「状態」を持つパラメタは、ConfigでなくRequestに移譲する
  - 処理中になんらか汚染されているか判定が難しいので（cloneしておくことも考えられますが、スマートではない）
  - Configは、アプリ起動時に一度だけ設定されるような値だけを入れるなど
- 各メソッド・フィルタは状態を返し、渡していく（Requestを加工していく、等）
  - 「テンプレートファイル名」も「状態」に含むべきと思います
- redirectなどの早期exitを廃止（現在擬似Exit例外で回避していますが、これもテスト対応のためにやめるべきでしょう）

## 現状の設計のままテストをするなら

色々なところにユニットテスト中か確認するIFをつくり、「抜き取り」「リセット」をするためのスイッチをつける（[現在、取り急ぎそのようにしていますが、スマートといえない](https://github.com/fc2blog/blog/blame/f50cad6c2ee30607470ff874979c9bce9af4649f/app/src/Web/Request.php#L51)））ことになるかと思います。

ただ、そのようにすると、事情に詳しくないと「テストが書けない」「状態をどこに追加すべきか分かりづらい」ので、好ましくはないかなと思います。

テストの書きやすさを上げないかぎり、開発者が気軽にテストを書かなくなります（私もきびしい）、そこの解決は早めにできればなとおもわれます、ご検討いただければ幸いです。

**Comment by fc2dev** [comment]
@uzulla 
ご提案をいただいた通り、改善対応をお願いいたします。

**Comment by uzulla** [comment]
@fc2dev 

まだ完全ではありませんが、一旦 #93 と、続くテスト実装 #114 で当座やりたい所は可能となりました。
Model系のシングルトンや、Configなどのグローバル変数的なものは随時削減していきます。
上記がマージされたらば、一旦本件はクローズしたいと思います。

**Comment by uzulla** [comment]
マージありがとうございました、クローズします。
