### ISSUE TITLE
管理画面において、素PHPからTwigテンプレートエンジンへ置き換え

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#77]
## 作業

作業ブランチ： https://github.com/uzulla/fc2blog/tree/convert-to-twig

- [x] Controller改修(作業をしながら)
- [x] Controllerリファクタリング（作業しながら）
- layout.twig
  - [x] PC
  - [x] SP
- `View/admin`以下のテンプレートをコンバート(約100個)
  - [x] admin/comments/*
  - [x] admin/blogs/*
  - [x] admin/entries/*
  - [x] admin/tags/*
  - [x] admin/common/*
  - [x] admin/layouts/* (ajax,json,download.phpは不要なので移設せず）
  - [x] admin/users/*
  - [x] admin/files/*
  - [x] admin/blog_plugins/*
  - [x] admin/categories/*
  - [x] admin/blog_templates/*
  - [x] admin/blog_settings/*

***

テストを増やしてほしいというご依頼から、様々な検討をしている一環です。

**以下は「管理画面」についてのことであって、動的なコードを生成する必要があり、自由度をさげたくないユーザー側の画面については検討するものではありません。**

## 課題

現在、`Web\Controller\Controller::layout`、`Web\Controller\Controller::display`のHTML生成は、コントローラーに設定された`$this->data`をextractして現在のスコープのローカル変数化した後、テンプレートファイルを`include`して評価する形で実現されています。

これはPHPファイルをそのままテンプレートとして活用する典型的なテクニックですので、これはこれでとおもわれますが、現在テンプレート内で直接Configなどをコールしている箇所があり、複数のデータソースからテンプレートがレンダリングされているのはテストの視点からは少々問題です。

## 改善

`Config::get`など、必要なものがあるなら必要なものを`$this->data`に事前登録すべきと思われます。それによって、テストはHTMLをパースせずに生のデータ(`$this->data`)で簡単に、正しくロジックを検証することが出来ます。

最悪でも、`Config`のインスタンスを`$this(controller)->data`に入れておくべきで、直接`Config::get(〜)`といった記述はテンプレートから外すべきかなと思います。

（このために訪問者向けのレンダラメソッドと管理画面のレンダラメソッドは別になります）

## さらなる改善

`extract()`してPHPをレンダリングする場合、テンプレートファイルから見て、呼び出されてみるまでは変数が存在するか自明ではありません。これは品質を上げるためのコードの静的解析においてはかなり厳しい条件となります。(ダミーのアノテーションを大量に書くなどのテクニックもありますが)

特に動的なPHPテンプレートが生成できる必要がない管理画面においては、PHPを直接テンプレートとせず、Twigなど安全でシンプルなテンプレートエンジンへの置き換えは検討できませんでしょうか？

テスト性も向上しますし、PHPをテンプレートエンジンとして使うのはどうやっても危険です。
（`h()`などを適切にいれればよいですが、ヒューマンエラーは最初からとり除くべきです）

**かさねてですが、これはテンプレートを自由にいじったりしない、静的である管理画面の話であって、ユーザー側画面の話ではありません**（コメント投稿画面は、そうしてもよいとも思いますが）

**Comment by fc2dev** [comment]
@uzulla 
テンプレート側からConfigへの依存を減らすために、テンプレートで利用すべきデータを
事前登録する改善について、実施をお願いいたします。

テンプレートエンジンについてはTwigへの置き換えをお願いします。
他に利用が推奨されるものがあれば別途ご提案ください。

**Comment by uzulla** [comment]
![image](https://user-images.githubusercontent.com/870716/92308381-1e62fe80-efd8-11ea-819b-63b557076f22.png)

約半分到達。

**Comment by uzulla** [comment]
@fc2blog

https://github.com/fc2blog/blog/pull/131
管理画面系をすべて書き換えいたしました、よろしければマージをお願いいたします。

元の通り、ユーザー系画面はノータッチですが、ユーザー変更のできない固定の画面（コメント投稿など）はTwigに変換しても良いかなと思います（別タスクとして行います）

**Comment by uzulla** [comment]
@fc2dev 確認とマージありがとうございました。
本件クローズいたします。
