### ISSUE TITLE
ユーザーテンプレート生成用タグのテストコード作成

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#78]
## 作業

- [x] リストアップ＆調査
- [x] テストコード
- [ ] 変換

***

https://github.com/fc2blog/blog/issues/78#issuecomment-717675106
に記載したが、

現在のテンプレート用のタグ（のPHPコード）は、その内で子孫タグが用いるデータを生成しており、変数スコープがフラットである前提の設計になっている。
そのために、現在想定される手法ではヘルパー関数などへの切り出しが困難（extract,compactを多用すれば解決できるが、良い解決策に見えない）なので、いったんテスト制作でヘルパータグの品質担保までとする。

## 以下は当初の目的であったが、完遂しなかった。

***

現在、タグを置換するために大量にタグとPHP生コードを置換するコードが`fc2_template.php`にあります。

https://github.com/fc2blog/blog/blob/127cfdf9b492596ea09c550ebb80fed99246dd26/app/config/fc2_template.php#L32

上記のような「ロジック」を置換するPHPコードをベタ書きするのは見通しが悪く、あまり安全にみえません。

可能ならば、そういったロジックをリストアップし、Wrapするヘルパー関数化して見通しをよくすることを提案いたします。

(現代のPHPは十分に高速なので、関数コールのコストを考える必要はないかと思われます)

```
\Fc2blog\Model\Model::load(\'BlogPlugins\')->findByDeviceTypeAndCategory($this->getDeviceType(), \Fc2blog\Config::get(\'BLOG_PLUGIN.CATEGORY.FIRST\'), $blog_id);
```

こういったコード片を

```
\Fc2blog\Template\Helper::getSpPluginFirst($this);
```

などとするということです。（究極、タグ一つにつき、１メソッドにしたほうがよいのですが、ifやforがあるので、全部は難しそうですね）

メリットとして、このPHPを生成する「文字列」が、できるだけPHPコードとして解釈できるようになり、コードの健全性をたもったり、このような圧縮した書き方をしなければならない場所で省略されがちな入力値チェックを余裕をもっていれる事が可能になります。リファクタも容易になるでしょう。

**Comment by fc2dev** [comment]
@uzulla 
本件、ご対応をお願いします。

**Comment by uzulla** [comment]
## ヘルパ化について
- `fc2_template`自体をいじっても複雑度をすごく改善させる修正がぱっと思いつかない。
- echo系タグは良いが、if,foreach系のブロック系は単にヘルパ等にするのが難しい。
- ifの中身をすべてクロージャで書くと注入が成立するようになる？
```
function hoge($inner){
  if($some_thing){
  	(function{?>($inner)<?php})();
  }
}
```
  - 生成されるコードがややこしくなるし、テンプレート生成機に手をいれないといけないのがつらそう。

## テスト
- 当座の目的はテストなのだから、「タグが健全か？」（エラーなくPHPとして実行できるか？）というテストを書く方法を考えたほうがよさそう。
- 手法として、全部のタグが動く本物のテンプレートをつくり、正しく動作するか確認するのは大変そうに見える
- ダミーテンプレート生成エンジンを作り、そのPHPを実行して評価するのは悪くなさそう（ただ、本物のテンプレート生成器に追従する必要がある）
- 単純に量が多いので大変ではある

## その他
- 多くの場合、コールされる関数をstaticにすればモデルをファクトリから作らずにすみそうだが（コードがシンプルになりそうだが）。そうできない（そうするとおかしくなる）ものがあるかもしれない、要調査。

**Comment by uzulla** [comment]
一旦`fc2_template.php`に定義された各種定義のリファクタリングは取りやめたい。
（if, foreachがネスト・依存しており、これを適切に抽象化するアイディアが不足した）
本質的な作業ではなくなってきた。

#136 のテストにより、タグの動作確認・品質は担保できるものと思われるので、一度マージし、将来的に対応したい。

タイトルをユーザーテンプレートヘルパーのリファクタリングから、ユーザーテンプレート用タグのテスト作成に変更する。

`fc2_template.php`のリファクタリング自体はまた別ISSUEにて検討をすすめる。

**Comment by uzulla** [comment]
#168 にて対応したためクローズ
