### ISSUE TITLE
本blogの対応デバイス、およびConfigのALLOW_DEVICES 周辺につきまして

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#83]
現状、以下のようなデバイスが設計（設定）としては考慮されておりますが、

https://github.com/fc2blog/blog/blob/2c92bebecf766ad4b76eaf05c1d0af7c097062b6/app/config/app.php#L8-L12

実際の設定や処理をみると、以下のようなコードで対応機種をしぼりこんでいるようです。

https://github.com/fc2blog/blog/blob/2c92bebecf766ad4b76eaf05c1d0af7c097062b6/app/config/app.php#L59-L62

（（（
なお、テンプレートの更新系コードを調査している時にきづきました、以下のあたりで、デバイス未指定時の挙動でガラケーとタブレットがでてこないことから追いかけて気づきました
https://github.com/fc2blog/blog/blob/2c92bebecf766ad4b76eaf05c1d0af7c097062b6/app/src/Model/BlogTemplatesModel.php#L152-L169
）））

実際のところ、テンプレート編集画面でもPC,SPしかありませんし、フィーチャーフォン（携帯・ガラケー）とタブレットは明示的に切り捨てたものということでよいでしょうか？また、これらの復活の予定はありますでしょうか？

現状、テンプレート保存などでも意味なくガラケーとタブレットのテンプレートを生成したりしており、不要ならば削除したいと考えております。

（現代においては、タブレットはPC用のテンプレートでよいでしょうし、ガラケーはもはやという気がいたします）

**Comment by fc2dev** [comment]
@uzulla 
レスポンシブデザインのテンプレートも増えてきていることから、
PC・スマホの区別も不要になりつつある状況ですが、
PC・スマホのくくりだけ維持をしておき、それ以外は撤廃としていただいて問題ありません。

**Comment by uzulla** [comment]
@fc2dev 

ありがとうございます、承知しました。

**Comment by uzulla** [comment]
#86 に引き継ぎ、本ISSUEはクローズします。
