### ISSUE TITLE
空のtemplate_comment.js？

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#92]
https://github.com/fc2blog/blog/blob/2c92bebecf766ad4b76eaf05c1d0af7c097062b6/app/config/fc2_template.php#L400

より参照されている、

https://github.com/fc2blog/blog/blob/2c92bebecf766ad4b76eaf05c1d0af7c097062b6/public/js/template_comment.js

ファイルが空ファイル？の模様。

意味がないのであれば削除とおもいますが、なにか意味があるファイルでしょうか？
（テンプレート変換のタグは残すにせよ）

**Comment by fc2dev** [comment]
@uzulla 
https://help.fc2.com/blog/manual/group101/1410

コメントを装飾するためのJSファイルを読み込むための変数の残骸のようです。
OSS版では不要ですが、テンプレート変換のタグ自体は残しておいていただきたいです。

**Comment by uzulla** [comment]
@fc2dev 

では、

```
'<%template_comment_js>'     => ''/* {多少の説明と本ISSUEへのリンク記載} */,
```

と、タグをのこした上で処理は削除し、

```
/template_comment.js
```

は削除でいかがでしょうか。

将来必要になればまた実装することは容易いと思います。

**Comment by fc2dev** [comment]
@uzulla 
ご提案いただいた対応にて、よろしくお願いいたします。

**Comment by uzulla** [comment]
#168 にて対応したためクローズ
