### ISSUE TITLE
提案：自前のルーターを、定番のルーターに変更

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#95]
現状、ifや正規表現を用いたルーティングを行っているが、分かりづらいので一般的なルーター(nikic/fastrouteなど)への置換を行い、宣言的にしたい。

## 課題
現在のコードは（特に）管理画面においてStrutsスタイルの「クラス」「アクション」をURLから取る設計になっているが、パターンによってDenyする格好となっており、存在するすべてのRouteが把握できないことや、本当に危険なパターンがDenyできているかが怪しいです。Denyリスト方式より、Allowリスト方式のほうがセキュリティ的にも望ましいといえます。

## デメリット
デメリットとして、今後はクラスやアクション追加時にルート定義をなんらか追加する必要があるが、大した手間ではないかと思われる。

現在、一部のルートはクエリパラメーター`mode=Class&process=Action`のような形式になっているが、`/mode/action`のような一般的な形式に一部書き換える必要がある。（そうしないことは技術的に可能ではあるが、そうしないと、宣言的にならないため）

つまり、URLが変わる。ただ、基本的にそのようなものを多用しているのは管理画面なので、ブログとしてのパーマリンクを壊すことはないのではないかとおもわれる。

**Comment by fc2dev** [comment]
@uzulla 
fastRouteを採用される場合は、ライセンス体系が異なるため、
必要な表示をReadmeに入れる前提であれば、採用していただいて問題ありません。

**Comment by uzulla** [comment]
アプリ全体を理解するにつれ、アクション（とりうるURLと、呼ばれるメソッド）が明確になれば課題は解決できるようにおもわれ、急ぎ対応する必要はなさそうと判断しましたので一度クローズします。
（課題を解決するのに、ルーター導入を必須としなくてよいと判断できたので）

https://github.com/fc2blog/blog/issues/108#issuecomment-717998303
の方向ですすめて、全アクションが明確にできた後、改めて導入を検討をしたいと思います。
