### ISSUE TITLE
現在では不要なPolyfil削除や、一箇所でしかつかわれていない関数のインライン化

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#97]
`common_functions.php`にある関数で、不要かなとおもわれるものがいくつかある。
（対応の結果、common_functionsではなく、html_helper_functions になればよいなと思う）

## 不要なPolyfill（7.3以降と規定したので、不要になるはず）
- `lcfirst` https://www.php.net/manual/ja/function.lcfirst.php
- `is_countable` https://www.php.net/manual/ja/function.is-countable.php

## 一箇所でしか使われていない関数
- `setLanguage` => インラインか、`Util\i18n`とかのクラスをつくってそちらに移動しても良さそう

## クラスに移動してもよさそうな関数
- `getServerUrl` => `Url`に
- `pascalCase`, `snakeCase`, `camelCase` => `Util\String`などに…

## IE対応
```
    // IE11のエディター対応
    if (stristr($_SERVER['HTTP_USER_AGENT'], 'trident')) {
      header('X-UA-Compatible: IE=EmulateIE10');
    }
```
まだ必要か？
JSのWYSIWYG Editorの都合かとは思うので、あちらのバージョンをあげれば治るか？

 => 調査したところ https://github.com/Studio-42/elRTE 最終更新日が8年前で、公式サイトも2015にはおちているので、ディスコンとなっている模様。別途対応が必要ではないかと思う。
　機能が十分か検討が必要だが、まだ活発なTinyMCEなどに置き換えが現実的かと思う。

**Comment by fc2dev** [comment]
@uzulla 
polyfillは削除いただいて構いません。
関数の移動はご提案通り実施ください。

IEはサポート対象外としているため、その処理は不要です。
エディタの置き換えは、折を見て実施できればと考えています。

**Comment by uzulla** [comment]
マージありがとうございました、こちらクローズいたします。
