### ISSUE TITLE
提案：Debugクラスの、ロガーと、フォーマッターの分離、整理整頓。

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#98]
Debug.phpは責務が単純ではないため、ロガーと、整形を分離したほうが良いかと思われます

また、名前もDebugからLog(ger)に変更し、その中の一部機能としてDebug logも出せる、という扱いにしたほうが良さそうかと思います（現在ログを取る機能がないのですこし不便なので）

## 現状の課題
- 画面に出すスタイル（昨今において、これが嬉しいユースケースはあるのか疑問）
- 色々な機能があるようだが、使い方のドキュメントがない（ので、おそらくだれも活用していない？）
  - 出力先が複雑（HTMLとして出力し、ビューワーする機能がある？）

## 現在あり珍しい機能
- （セッションに保持する事で）リダイレクト前、後の情報をつなげたログ出力をできる（模様）
  - 便利なのだろうか？（使い方が不明で、試せていない。便利なら使いたい）

**Comment by fc2dev** [comment]
@uzulla 
ご対応、よろしくお願いいたします。

**Comment by uzulla** [comment]
@fc2dev 

Debugクラスについて調査し、実際の各種モードの動作確認と挙動確認をおこないました。

デバッグモード:1はリダイレクトを含まないページだとある程度のログが画面に表示されますが、リダイレクトがはさまると正常にサイトが動作しません（そういうものなのだと思います）デバッグモード4は、モード１とほぼ同じで出力文字列がHTMLでなくなります。
どちらも画面にログを出したいケースでは楽かとおもいますが、「大量のサーバーでログ集約機構がない」ような環境を除けば、ログファイルに出力しておいてtailすればよいかと思われますので、今では不要な機能かと思います。


デバッグモード2および3は、リダイレクトを含むページでも動作するようにログを`/temp/debug_html`内にファイルに保存した上で、`http://localhost:8080/admin/common/debug`というURLのビューワーで参照して表示したいのだろう、という所までは確認できました。
しかし、`debug_html`内に実際にデータを書き出す`Debug::output`がどこからもコールされていないので、いまは使われていない（ログが書き出されないのでうごかない）モードなのかと思われます。


Debugという名称からも、開発者がソースコードを書く際にのみ参照するものとおもわれます。
となると、2,3が動作しないのであれば当時から不要であったのでしょうし、1,2はログファイルを見れる現場では、やはり不要かなとおもわれました。
（なお、デバッグモード５は、私が「必要なのだろうな」と追加したものなので、昔は存在しません）


よって、Debugクラス自体は不要と判断しました。
代わりに一般的なLoggerを導入し、デバッグログレベルに応じたログ出力をログファイルに行うように変更したいと思います。

**Comment by uzulla** [comment]
マージありがとうございました、こちらクローズいたします。
