### ISSUE TITLE
スーパーグローバルの削減

### ISSUE THREAD

**Issue by uzulla** [fc2blog/blog#99]
スーパーグローバルの（可能な範囲での）削減。主な目的は挙動を揃えるため。

- [x] $_SERVER （一部テストに残存
- [x] $_COOKIE （一部テストに残存
- [x] $_POST
- [x] $_GET
- [x] $GLOBALS
- [x] $_FILES
- [x] $_REQUEST
- [x] $_ENV
- [ ] $_SESSION （モデルのvalidationの奥深くで一部使われており、現段階では諦め

## 手法
Request インスタンスに寄せていく
testについては

**Comment by fc2dev** [comment]
@uzulla 
進めていただきたいです。

**Comment by uzulla** [comment]
全廃はできませんでしたが、当座可能な範囲で完了いたしましたので、クローズいたします。
`$_SESSION`系はモデル周りの重リファクタ時に対応することとします。
